### ISSUE TITLE
Page render fails with Uncaught TypeError: Cannot read properties of undefined (reading 'getParents')

### ISSUE THREAD

**Issue by tfoote** [http404error/roseco#23]
I suspect that a js dependency has updated and the site needs to move to a newer version of the API.

For example visiting https://http404error.github.io/roseco/graph.html?id=ros.json&focus=rclcpp&height=1&depth=2&tred=standard&metagroup=false&colorby=Health&direction=LR

I see the following error in the browser console

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getParents')
    at narrow_focus (xtrace_graph.js:329:51)
    at XTraceDAG.adjustSettingsPrime (xtrace_graph.js:385:3)
    at XTraceDAG.adjustSettings (underscore.js:701:23)
    at new XTraceDAG (xtrace_graph.js:566:7)
    at callback (graph.html?id=ros.json&focus=rclcpp&height=1&depth=2&tred=standard&metagroup=false&colorby=Health&direction=LR:51:19)
    at json_batch_callback (xtrace_utils.js:79:31)
    at d3.v3.min.js:1:750
    at Object.<anonymous> (d3.v3.min.js:2:23988)
    at Object.n (d3.v3.min.js:1:1104)
    at XMLHttpRequest.r (d3.v3.min.js:2:22980)
```

**Comment by http404error** [comment]
I believe the issue is that the data being used for RosEco currently is very out of date (Oct 2014) and does not contain 'rclcpp' at all (nor is there any awareness of distros etc). This problem has probably always existed with the rosindex links. The following link still works: http://http404error.github.io/roseco/graph.html?id=ros.json&focus=rviz&height=1&depth=2&tred=standard&metagroup=false&colorby=Health&direction=LR

(Filed https://github.com/http404error/roseco/issues/24)

**A future for RosEco?**
@tfoote, is RosEco useful to any developers that you are aware of? If so, I may attempt to update RosEco to tie in better to rosindex (which I'm delighted to see has been well-adopted, by the way). However, I certainly won't be hurt if you simply remove the link to RosEco. Given how long it took for anyone to report how broken/out-of-date it is, I doubt it was being used much. Or, if you think package relationship visualization is _very_ useful, it might be a better idea to develop an entirely new graph viz for rosindex...

**Comment by tfoote** [comment]
@http404error It would be great to get a graph viz for rosindex. Currently we only have the list based ones.

If it is that far out of date it won't be useful. The rosindex data is recrawled nightly. If we could leverage that crawl to regenerate the visualizations that would be great. Maybe just integrate the javascript into the rosindex site using the updated crawl data. Another option might be to to update the roseco to leverage the rosdistro cache which we generate much faster which I think has a superset of the content in your json format.
